// ============================================================
// Express Pizza — Thermal Printer Driver TCP (Sprint 5)
// ============================================================

const net = require('net');
const prisma = require('../lib/prisma');

// In-memory queue to prevent overwhelming the printer with rapid tasks
const printQueue = [];
let isPrinting = false;

/**
 * Main print function (adds to processing queue)
 * @param {Buffer} buffer Raw ESC/POS generated by receiptService
 * @param {string} ip Network IP of the printer
 * @param {number} port Port (usually 9100)
 */
async function printBuffer(buffer, ip, port = 9100) {
    if (!ip) {
        console.warn('⚠️ [Printer] Target IP is undefined. Print skipped.');
        return false;
    }

    return new Promise((resolve, reject) => {
        printQueue.push({ buffer, ip, port, resolve, reject });
        processQueue();
    });
}

async function processQueue() {
    if (isPrinting || printQueue.length === 0) return;

    isPrinting = true;
    const task = printQueue.shift();

    console.log(`[Printer] Attempting to print to tcp://${task.ip}:${task.port}...`);

    const client = new net.Socket();

    // Safety timeouts: don't hang server if printer is unplugged
    client.setTimeout(5000);

    client.connect(task.port, task.ip, () => {
        // Connected! Drain the buffer into the printer's TCP port
        client.write(task.buffer, () => {
            console.log(`[Printer] ✅ Successfully sent ${task.buffer.length} bytes to ${task.ip}`);
            client.destroy(); // Close connection
            task.resolve(true);
        });
    });

    client.on('timeout', () => {
        console.error(`[Printer] ❌ Timeout connecting to ${task.ip}:${task.port}. Is the printer on?`);
        client.destroy();
        task.resolve(false); // Resolve false rather than strict reject to avoid crash
    });

    client.on('error', (err) => {
        console.error(`[Printer] ❌ Network error while printing:`, err.message);
        client.destroy();
        task.resolve(false);
    });

    client.on('close', () => {
        isPrinting = false;
        // Small delay between receipts to let physical printhead catch up
        setTimeout(processQueue, 500);
    });
}

/**
 * Wraps printBuffer and logs to DB.
 */
async function sendReceiptToHardware(orderId, type, rawBuffer, restaurantId, ip) {
    // 1. Log receipt intended for print to DB (so it can be reprinted later)
    await prisma.receipt.create({
        data: {
            orderId,
            restaurantId,
            type,
            printerIp: ip,
            rawData: rawBuffer // Saved to DB as Bytes
        }
    });

    // 2. Dispatch to networking queue
    await printBuffer(rawBuffer, ip);
}

module.exports = {
    printBuffer,
    sendReceiptToHardware
};
